[profile.default]
optimizer = true
via_ir = true
evm_version = "cancun"
auto_detect_remappings = false
optimizer_runs = 100_000
solc_version = "0.8.28"
no_match_contract = "Medusa"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.deploy]
ffi = true
fs_permissions = [{ access = "read", path = "./airdrop.json"}, { access = "read", path = "./image.svg"}]

[fuzz]
runs = 10_000_000
max_test_rejects = 100_000_000

[invariant]
fail_on_revert = true
runs = 1_000
depth = 50
