[profile.default]
optimizer = true
via_ir = true
evm_version = "cancun"
auto_detect_remappings = false
optimizer_runs = 100_000
solc_version = "0.8.28"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[fuzz]
runs = 10_000_000
max_test_rejects = 100_000_000
