[profile.default]
optimizer = true
via_ir = true
evm_version = "cancun"
auto_detect_remappings = false

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[fuzz]
runs = 100_000
max_test_rejects = 1_000_000
